"""
8 个核心形态参数化定义（Section 08）
A1~A3（做多）· B1~B3（做空）· C1~C2（过滤）
所有数值为默认阈值，通过 config.py 覆盖。
"""
from __future__ import annotations

from ..models import PatternDefinition, PatternField

# ──────────────────────────────────────────────────────────────────────────────
# A1  上升后平台整理（做多，bull_trend / ranging）
# ──────────────────────────────────────────────────────────────────────────────
A1 = PatternDefinition(
    pattern_id   = 'A1',
    pattern_name = '上升后平台整理',
    category     = 'A',
    direction    = 'long',
    timeframes   = ['4h', '1h', '15m'],
    min_bars     = 45,
    score_pass   = 75.0,
    score_high   = 88.0,
    regime_filter = ['bull_trend', 'ranging'],
    fields = [
        # ── 确认字段 ─────────────────────────────────────────────────────────
        PatternField('A1_F01', 'A1', '前序涨幅',
            field_type='confirm', is_required=True,
            indicator='max_advance_45', operator='>', param_a=0.15,
            lookback=45, weight=1.0),
        PatternField('A1_F02', 'A1', '平台振幅',
            field_type='confirm', is_required=True,
            indicator='platform_range_ratio', operator='ratio_lt',
            ref_indicator='max_advance_45', ref_multiplier=1.0,
            param_a=0.30, lookback=30, weight=1.0),
        PatternField('A1_F03', 'A1', '平台低点稳定',
            field_type='confirm', is_required=True,
            indicator='low', operator='all_above',
            ref_indicator='platform_start_price', ref_multiplier=0.95,
            lookback=30, weight=0.8),
        PatternField('A1_F04', 'A1', '长均线向上',
            field_type='confirm', is_required=True,
            indicator='ma120', operator='slope_positive',
            lookback=10, weight=0.9),
        PatternField('A1_F05', 'A1', '价格在MA120上方',
            field_type='confirm', is_required=False,
            indicator='close_above_ma120', operator='count_gte',
            param_a=21, lookback=30, weight=0.8),
        PatternField('A1_F06', 'A1', 'ATR收敛',
            field_type='confirm', is_required=False,
            indicator='atr14', operator='ratio_lt',
            ref_indicator='atr_ma30', ref_multiplier=1.0,
            param_a=0.85, weight=0.7),
        PatternField('A1_F07', 'A1', '缩量整理',
            field_type='confirm', is_required=True,
            indicator='vol_ma20', operator='ratio_lt',
            ref_indicator='vol_ma_prev', ref_multiplier=0.80,
            param_a=1.0, weight=0.8),
        PatternField('A1_F08', 'A1', '平台下沿测试',
            field_type='confirm', is_required=False,
            indicator='support_touch_count', operator='count_gte',
            param_a=2, lookback=30, weight=0.6),
        PatternField('A1_F09', 'A1', '回调不超先涨50%',
            field_type='confirm', is_required=True,
            indicator='pullback_ratio', operator='ratio_lt',
            ref_indicator='max_advance_45', ref_multiplier=0.50,
            param_a=1.0, lookback=30, weight=1.0,
            description='回调幅度<前序涨幅50%，排除冲高回落'),
        # ── 排除字段 ─────────────────────────────────────────────────────────
        PatternField('A1_E01', 'A1', '高点递降',
            field_type='exclude', is_required=True,
            indicator='consecutive_lower_highs_3', operator='bool_true',
            penalty=30.0),
        PatternField('A1_E02', 'A1', '放量阴线',
            field_type='exclude', is_required=False,
            indicator='bear_vol_spike', operator='bool_true',
            penalty=25.0),
        PatternField('A1_E03', 'A1', '长均线拐头',
            field_type='exclude', is_required=True,
            indicator='ma120', operator='slope_negative',
            lookback=3, penalty=35.0),
        PatternField('A1_E04', 'A1', '跌破平台',
            field_type='exclude', is_required=True,
            indicator='platform_break', operator='bool_true',
            penalty=50.0),
        # ── 触发字段 ─────────────────────────────────────────────────────────
        PatternField('A1_T01', 'A1', '突破做多',
            field_type='trigger', is_required=False,
            indicator='platform_breakout', operator='bool_true',
            description='breakout'),
        PatternField('A1_T02', 'A1', '回踩做多',
            field_type='trigger', is_required=False,
            indicator='platform_pullback', operator='bool_true',
            description='pullback'),
    ],
)

# ──────────────────────────────────────────────────────────────────────────────
# A2  长均线托底横盘（做多，bull_trend）
# ──────────────────────────────────────────────────────────────────────────────
A2 = PatternDefinition(
    pattern_id   = 'A2',
    pattern_name = '长均线托底横盘',
    category     = 'A',
    direction    = 'long',
    timeframes   = ['4h', '1h', '15m'],
    min_bars     = 40,
    score_pass   = 75.0,
    score_high   = 88.0,
    regime_filter = ['bull_trend'],
    fields = [
        PatternField('A2_F01', 'A2', 'MA120持续上行',
            field_type='confirm', is_required=True,
            indicator='ma120', operator='slope_positive',
            lookback=10, weight=1.0),
        PatternField('A2_F02', 'A2', '收盘在MA120上方',
            field_type='confirm', is_required=True,
            indicator='close_above_ma120', operator='count_gte',
            param_a=23, lookback=30, weight=1.0),
        PatternField('A2_F03', 'A2', '下探后收回',
            field_type='confirm', is_required=False,
            indicator='ma120_touch_recover', operator='count_gte',
            param_a=1, lookback=30, weight=0.9),
        PatternField('A2_F04', 'A2', '短中均线缠绕',
            field_type='confirm', is_required=False,
            indicator='ma20_ma60_spread_pct', operator='<',
            param_a=0.015, weight=0.7),
        PatternField('A2_F05', 'A2', '振幅适中',
            field_type='confirm', is_required=False,
            indicator='avg_bar_range', operator='between',
            param_a=0.008, param_b=0.040, weight=0.6),
        # ── 排除字段 ─────────────────────────────────────────────────────────
        PatternField('A2_E01', 'A2', '持续压在MA60下',
            field_type='exclude', is_required=True,
            indicator='close', operator='all_below',
            ref_indicator='ma60', lookback=5, penalty=35.0),
        PatternField('A2_E02', 'A2', '跌破MA120',
            field_type='exclude', is_required=True,
            indicator='ma120_break_confirm', operator='bool_true',
            penalty=40.0),
        PatternField('A2_E03', 'A2', '放量阴线',
            field_type='exclude', is_required=False,
            indicator='bear_vol_spike', operator='bool_true',
            penalty=15.0),
        # ── 触发字段 ─────────────────────────────────────────────────────────
        PatternField('A2_T01', 'A2', '回踩MA120',
            field_type='trigger', is_required=False,
            indicator='ma120_touch_recover', operator='bool_true',
            description='ma_touch'),
        PatternField('A2_T02', 'A2', '放量突破',
            field_type='trigger', is_required=False,
            indicator='new_high_vol_breakout', operator='bool_true',
            description='breakout'),
    ],
)

# ──────────────────────────────────────────────────────────────────────────────
# A3  假跌破回收（做多，bull_trend / ranging）
# ──────────────────────────────────────────────────────────────────────────────
A3 = PatternDefinition(
    pattern_id   = 'A3',
    pattern_name = '假跌破回收',
    category     = 'A',
    direction    = 'long',
    timeframes   = ['4h', '1h', '15m'],
    min_bars     = 30,
    score_pass   = 72.0,
    score_high   = 85.0,
    regime_filter = ['bull_trend', 'ranging'],
    fields = [
        PatternField('A3_F01', 'A3', '跌破支撑',
            field_type='confirm', is_required=True,
            indicator='support_break_pct', operator='between',
            param_a=-0.015, param_b=0.0, weight=1.0),
        PatternField('A3_F02', 'A3', '快速收回',
            field_type='confirm', is_required=True,
            indicator='recovered_above_support', operator='count_gte',
            param_a=1, lookback=3, weight=1.0),
        PatternField('A3_F03', 'A3', '跌破非持续放量',
            field_type='confirm', is_required=False,
            indicator='vol_ratio', operator='<',
            param_a=1.8, weight=0.9),
        PatternField('A3_F04', 'A3', '下影线承接',
            field_type='confirm', is_required=False,
            indicator='lower_shadow', operator='ratio_gt',
            ref_indicator='body_size', ref_multiplier=1.0,
            param_a=1.5, weight=0.7),
        PatternField('A3_F05', 'A3', '相对大盘抗跌',
            field_type='confirm', is_required=False,
            indicator='outperform_btc_down', operator='bool_true',
            weight=0.6),
        # ── 排除字段 ─────────────────────────────────────────────────────────
        PatternField('A3_E01', 'A3', '二次跌破',
            field_type='exclude', is_required=True,
            indicator='secondary_breakdown', operator='bool_true',
            penalty=50.0),
        PatternField('A3_E02', 'A3', '跌破过深',
            field_type='exclude', is_required=True,
            indicator='support_break_pct', operator='<',
            param_a=-0.02, penalty=30.0),
        PatternField('A3_E03', 'A3', '三均线压制',
            field_type='exclude', is_required=False,
            indicator='triple_ma_suppress', operator='bool_true',
            penalty=20.0),
        # ── 触发字段 ─────────────────────────────────────────────────────────
        PatternField('A3_T01', 'A3', '假跌破确认',
            field_type='trigger', is_required=False,
            indicator='false_breakdown_confirm', operator='bool_true',
            description='false_breakdown_confirm'),
    ],
)

# ──────────────────────────────────────────────────────────────────────────────
# B1  下跌中继（做空，bear_trend）
# ──────────────────────────────────────────────────────────────────────────────
B1 = PatternDefinition(
    pattern_id   = 'B1',
    pattern_name = '下跌中继',
    category     = 'B',
    direction    = 'short',
    timeframes   = ['4h', '1h', '15m'],
    min_bars     = 40,
    score_pass   = 75.0,
    score_high   = 88.0,
    regime_filter = ['bear_trend'],
    fields = [
        PatternField('B1_F01', 'B1', '前序下跌',
            field_type='confirm', is_required=True,
            indicator='max_decline_40', operator='>',
            param_a=0.15, lookback=40, weight=1.0),
        PatternField('B1_F02', 'B1', '均线空头排列',
            field_type='confirm', is_required=True,
            indicator='bear_ma_align', operator='bool_true',
            weight=1.0),
        PatternField('B1_F03', 'B1', '价格在MA120下方',
            field_type='confirm', is_required=True,
            indicator='close_below_ma120', operator='count_gte',
            param_a=16, lookback=20, weight=0.9),
        PatternField('B1_F04', 'B1', '反弹缩量',
            field_type='confirm', is_required=False,
            indicator='vol_ma20', operator='ratio_lt',
            ref_indicator='vol_ma_prev', ref_multiplier=0.75,
            param_a=1.0, weight=0.8),
        PatternField('B1_F05', 'B1', '反弹触均线回落',
            field_type='confirm', is_required=False,
            indicator='ma_rejection', operator='bool_true',
            weight=0.8),
        PatternField('B1_F06', 'B1', 'RSI偏弱',
            field_type='confirm', is_required=False,
            indicator='rsi14_local_high', operator='<=',
            param_a=55.0, weight=0.6),
        # ── 排除字段 ─────────────────────────────────────────────────────────
        PatternField('B1_E01', 'B1', '收复MA60',
            field_type='exclude', is_required=True,
            indicator='close_above_ma60_sustained', operator='bool_true',
            penalty=40.0),
        PatternField('B1_E02', 'B1', '低点不续创新低',
            field_type='exclude', is_required=False,
            indicator='recent_low_above_prior', operator='bool_true',
            penalty=25.0),
        PatternField('B1_E03', 'B1', '放量阳线',
            field_type='exclude', is_required=False,
            indicator='bull_vol_spike', operator='bool_true',
            penalty=20.0),
        # ── 触发字段 ─────────────────────────────────────────────────────────
        PatternField('B1_T01', 'B1', '反弹做空',
            field_type='trigger', is_required=False,
            indicator='ma20_rejection_zone', operator='bool_true',
            description='rebound_short'),
        PatternField('B1_T02', 'B1', '破位做空',
            field_type='trigger', is_required=False,
            indicator='range_breakdown', operator='bool_true',
            description='breakdown_short'),
    ],
)

# ──────────────────────────────────────────────────────────────────────────────
# B2  平台破位（做空，bear_trend / ranging）
# ──────────────────────────────────────────────────────────────────────────────
B2 = PatternDefinition(
    pattern_id   = 'B2',
    pattern_name = '平台破位',
    category     = 'B',
    direction    = 'short',
    timeframes   = ['4h', '1h', '15m'],
    min_bars     = 35,
    score_pass   = 76.0,
    score_high   = 88.0,
    regime_filter = ['bear_trend', 'ranging'],
    fields = [
        PatternField('B2_F01', 'B2', '先有平台',
            field_type='confirm', is_required=True,
            indicator='range_bar_count', operator='count_gte',
            param_a=15, lookback=35, weight=1.0),
        PatternField('B2_F02', 'B2', '有效跌破',
            field_type='confirm', is_required=True,
            indicator='close_below_platform', operator='bool_true',
            weight=1.0),
        PatternField('B2_F03', 'B2', '跌破后不收回',
            field_type='confirm', is_required=True,
            indicator='close_below_platform', operator='count_gte',
            param_a=2, lookback=5, weight=1.0),
        PatternField('B2_F04', 'B2', '跌破放量',
            field_type='confirm', is_required=False,
            indicator='vol_ratio', operator='>',
            param_a=1.2, weight=0.8),
        PatternField('B2_F05', 'B2', '反抽失败',
            field_type='confirm', is_required=False,
            indicator='dead_cat_bounce', operator='bool_true',
            weight=0.9),
        # ── 排除字段 ─────────────────────────────────────────────────────────
        PatternField('B2_E01', 'B2', '次根收回',
            field_type='exclude', is_required=True,
            indicator='close_recover_after_break', operator='bool_true',
            penalty=50.0),
        PatternField('B2_E02', 'B2', '跌破无量',
            field_type='exclude', is_required=False,
            indicator='vol_ratio', operator='<',
            param_a=0.7, penalty=20.0),
        PatternField('B2_E03', 'B2', '仅插针',
            field_type='exclude', is_required=True,
            indicator='wick_only_break', operator='bool_true',
            penalty=35.0),
        # ── 触发字段 ─────────────────────────────────────────────────────────
        PatternField('B2_T01', 'B2', '跌破做空',
            field_type='trigger', is_required=False,
            indicator='close_below_platform', operator='bool_true',
            description='breakdown_short'),
        PatternField('B2_T02', 'B2', '反抽失败做空',
            field_type='trigger', is_required=False,
            indicator='dead_cat_bounce', operator='bool_true',
            description='pullback_short'),
    ],
)

# ──────────────────────────────────────────────────────────────────────────────
# B3  空头趋势弱反弹（做空，bear_trend）
# ──────────────────────────────────────────────────────────────────────────────
B3 = PatternDefinition(
    pattern_id   = 'B3',
    pattern_name = '空头趋势弱反弹',
    category     = 'B',
    direction    = 'short',
    timeframes   = ['4h', '1h', '15m'],
    min_bars     = 30,
    score_pass   = 72.0,
    score_high   = 85.0,
    regime_filter = ['bear_trend'],
    fields = [
        PatternField('B3_F01', 'B3', 'Lower High×3',
            field_type='confirm', is_required=True,
            indicator='three_lower_highs', operator='bool_true',
            weight=1.0),
        PatternField('B3_F02', 'B3', '反弹不过前高',
            field_type='confirm', is_required=True,
            indicator='rebound_high', operator='ratio_lt',
            ref_indicator='prev_local_high', ref_multiplier=0.99,
            param_a=1.0, weight=0.9),
        PatternField('B3_F03', 'B3', '反弹速度慢',
            field_type='confirm', is_required=False,
            indicator='rebound_slope_ratio', operator='<',
            param_a=0.5, weight=0.8),
        PatternField('B3_F04', 'B3', '反弹缩量',
            field_type='confirm', is_required=False,
            indicator='rebound_vol_ratio', operator='<',
            param_a=0.7, weight=0.8),
        PatternField('B3_F05', 'B3', 'MACD零轴下',
            field_type='confirm', is_required=False,
            indicator='macd_bearish', operator='bool_true',
            weight=0.7),
        # ── 排除字段 ─────────────────────────────────────────────────────────
        PatternField('B3_E01', 'B3', '站上MA120',
            field_type='exclude', is_required=True,
            indicator='close_above_ma120', operator='count_gte',
            param_a=2, lookback=2, penalty=40.0),
        PatternField('B3_E02', 'B3', '连续放量阳线',
            field_type='exclude', is_required=False,
            indicator='bull_vol_large', operator='count_gte',
            param_a=2, lookback=10, penalty=25.0),
        PatternField('B3_E03', 'B3', '低点停止创新低',
            field_type='exclude', is_required=False,
            indicator='rising_lows_3', operator='bool_true',
            penalty=20.0),
        # ── 触发字段 ─────────────────────────────────────────────────────────
        PatternField('B3_T01', 'B3', '前高附近做空',
            field_type='trigger', is_required=False,
            indicator='rebound_rejection', operator='bool_true',
            description='rebound_short'),
    ],
)

# ──────────────────────────────────────────────────────────────────────────────
# C1  均线乱缠无趋势（过滤，ranging，filter_min=2）
# ──────────────────────────────────────────────────────────────────────────────
C1 = PatternDefinition(
    pattern_id   = 'C1',
    pattern_name = '均线乱缠无趋势',
    category     = 'C',
    direction    = 'neutral',
    timeframes   = ['4h', '1h', '15m'],
    min_bars     = 20,
    score_pass   = 0.0,
    score_high   = 0.0,
    regime_filter = ['ranging'],
    filter_logic  = 'any',
    filter_min    = 2,
    fields = [
        PatternField('C1_F01', 'C1', 'MA乱序',
            field_type='confirm', is_required=False,
            indicator='ma_order_changes', operator='>=',
            param_a=2, lookback=10, weight=1.0),
        PatternField('C1_F02', 'C1', '频繁穿MA60',
            field_type='confirm', is_required=False,
            indicator='ma60_cross_count', operator='>=',
            param_a=4, lookback=20, weight=1.0),
        PatternField('C1_F03', 'C1', '无方向高低点',
            field_type='confirm', is_required=False,
            indicator='no_directional_swings', operator='bool_true',
            weight=1.0),
        PatternField('C1_F04', 'C1', '高ATR无方向',
            field_type='confirm', is_required=False,
            indicator='high_atr_no_direction', operator='bool_true',
            weight=1.0),
    ],
)

# ──────────────────────────────────────────────────────────────────────────────
# C2  极端插针结构（过滤，any，filter_min=1）
# ──────────────────────────────────────────────────────────────────────────────
C2 = PatternDefinition(
    pattern_id   = 'C2',
    pattern_name = '极端插针结构',
    category     = 'C',
    direction    = 'neutral',
    timeframes   = ['4h', '1h', '15m'],
    min_bars     = 1,
    score_pass   = 0.0,
    score_high   = 0.0,
    regime_filter = [],   # any regime
    filter_logic  = 'any',
    filter_min    = 1,
    fields = [
        PatternField('C2_F01', 'C2', '单根振幅',
            field_type='confirm', is_required=False,
            indicator='bar_range_pct', operator='>=',
            param_a=0.08, weight=1.0),
        PatternField('C2_F02', 'C2', '频繁插针',
            field_type='confirm', is_required=False,
            indicator='long_wick_count', operator='>=',
            param_a=3, lookback=10, weight=1.0),
        PatternField('C2_F03', 'C2', '异常巨量',
            field_type='confirm', is_required=False,
            indicator='vol_ratio', operator='>',
            param_a=5.0, weight=1.0),
    ],
)

# ──────────────────────────────────────────────────────────────────────────────
# 注册表
# ──────────────────────────────────────────────────────────────────────────────
PATTERN_REGISTRY: dict[str, PatternDefinition] = {
    'A1': A1,
    'A2': A2,
    'A3': A3,
    'B1': B1,
    'B2': B2,
    'B3': B3,
    'C1': C1,
    'C2': C2,
}

ALL_PATTERNS: list[PatternDefinition] = list(PATTERN_REGISTRY.values())
